### ISSUE TITLE
add GALEX filters to sfd.extinctions array

### ISSUE THREAD

**Issue by moustakas** [dstndstn/tractor#99]
The `sfd.extinctions` array is missing GALEX--
  https://github.com/dstndstn/tractor/blob/main/tractor/sfd.py

Any chance these coefficients can be added (although I don't have the appropriate coefficients, off-hand)?

**Comment by schlafly** [comment]
I'm skeptical of very low values of FUV/SFD; I'd note the UV comparisons in this paper are tricky because only a small fraction of the sample has UV fluxes (faint stars), so one needs to be very careful in the modeling.  Josh Peek's UV modeling instead preferred high values for this quantity (~10).  I think F99 is a sane default.
